name: Mulesoft CI/CD Githubaction Pipeline

on:
  pull_request:
    branches: [ test ]
  push:
    branches: [ test ]

jobs:
  prvalidationbuild:
    if: github.event_name == 'pull_request'
    uses: jegoSFDC/mulesofttemplate/.github/workflows/ci-build.yml@main
    secrets:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}

  deploy-after-merge:
    if: github.event_name == 'push' && github.ref == 'refs/heads/test'
    uses: jegoSFDC/mulesofttemplate/.github/workflows/cd-deploy.yml@main
    secrets:
      CA_CLIENT_ID: ${{ secrets.CA_CLIENT_ID }}
      CA_CLIENT_SECRET: ${{ secrets.CA_CLIENT_SECRET }}
